export const TEXTILE_NEXUS_ABI = [
  // ── Errors ──────────────────────────────────────────────────────────────
  { type: "error", name: "Unauthorized",     inputs: [] },
  { type: "error", name: "InvalidInput",     inputs: [] },
  { type: "error", name: "NotFound",         inputs: [] },
  { type: "error", name: "InvalidState",     inputs: [] },
  { type: "error", name: "AlreadyProcessed", inputs: [] },
  { type: "error", name: "Expired",          inputs: [] },

  // ── Events ───────────────────────────────────────────────────────────────
  { type:"event", name:"ActorRegistered",        anonymous:false, inputs:[{indexed:true,name:"wallet",type:"address"},{indexed:false,name:"role",type:"uint8"},{indexed:false,name:"name",type:"string"}] },
  { type:"event", name:"ActorDeactivated",       anonymous:false, inputs:[{indexed:true,name:"wallet",type:"address"}] },
  { type:"event", name:"ActorReputationUpdated", anonymous:false, inputs:[{indexed:true,name:"wallet",type:"address"},{indexed:false,name:"newScore",type:"uint256"}] },
  { type:"event", name:"MaterialSourced",        anonymous:false, inputs:[{indexed:true,name:"materialId",type:"uint256"},{indexed:true,name:"supplier",type:"address"},{indexed:false,name:"fiber",type:"uint8"},{indexed:false,name:"weightKg",type:"uint256"},{indexed:false,name:"totalCost",type:"uint256"}] },
  { type:"event", name:"MaterialQualityApproved",anonymous:false, inputs:[{indexed:true,name:"materialId",type:"uint256"},{indexed:false,name:"grade",type:"uint8"},{indexed:true,name:"inspector",type:"address"}] },
  { type:"event", name:"MaterialQualityRejected",anonymous:false, inputs:[{indexed:true,name:"materialId",type:"uint256"},{indexed:true,name:"inspector",type:"address"},{indexed:false,name:"reason",type:"string"}] },
  { type:"event", name:"BatchMovedToDept",       anonymous:false, inputs:[{indexed:true,name:"batchId",type:"uint256"},{indexed:true,name:"dept",type:"uint8"},{indexed:true,name:"deptHead",type:"address"}] },
  { type:"event", name:"BatchDeptCompleted",     anonymous:false, inputs:[{indexed:true,name:"batchId",type:"uint256"},{indexed:true,name:"dept",type:"uint8"},{indexed:false,name:"costAdded",type:"uint256"}] },
  { type:"event", name:"BatchQCApproved",        anonymous:false, inputs:[{indexed:true,name:"batchId",type:"uint256"},{indexed:true,name:"inspector",type:"address"},{indexed:false,name:"notes",type:"string"}] },
  { type:"event", name:"BatchQCRejected",        anonymous:false, inputs:[{indexed:true,name:"batchId",type:"uint256"},{indexed:true,name:"inspector",type:"address"},{indexed:false,name:"notes",type:"string"}] },
  { type:"event", name:"BatchReadyForDispatch",  anonymous:false, inputs:[{indexed:true,name:"batchId",type:"uint256"},{indexed:false,name:"finalCost",type:"uint256"}] },
  { type:"event", name:"BatchRecalled",          anonymous:false, inputs:[{indexed:true,name:"batchId",type:"uint256"},{indexed:false,name:"reason",type:"string"}] },
  { type:"event", name:"DispatchConsensusUpdate",anonymous:false, inputs:[{indexed:true,name:"orderId",type:"uint256"},{indexed:false,name:"signer",type:"string"},{indexed:true,name:"signerAddress",type:"address"}] },
  { type:"event", name:"BatchDispatched",        anonymous:false, inputs:[{indexed:true,name:"orderId",type:"uint256"},{indexed:true,name:"batchId",type:"uint256"},{indexed:false,name:"courier",type:"string"},{indexed:false,name:"trackingNo",type:"string"}] },
  { type:"event", name:"TransitCheckpointAdded", anonymous:false, inputs:[{indexed:true,name:"orderId",type:"uint256"},{indexed:false,name:"location",type:"string"},{indexed:false,name:"timestamp",type:"uint256"}] },
  { type:"event", name:"BatchDelivered",         anonymous:false, inputs:[{indexed:true,name:"orderId",type:"uint256"},{indexed:true,name:"batchId",type:"uint256"},{indexed:true,name:"receiver",type:"address"}] },
  { type:"event", name:"DispatchFailed",         anonymous:false, inputs:[{indexed:true,name:"orderId",type:"uint256"},{indexed:false,name:"reason",type:"string"}] },
  { type:"event", name:"OwnershipTransferred",   anonymous:false, inputs:[{indexed:true,name:"batchId",type:"uint256"},{indexed:true,name:"from",type:"address"},{indexed:true,name:"to",type:"address"},{indexed:false,name:"reason",type:"string"}] },
  { type:"event", name:"PaymentReleased",        anonymous:false, inputs:[{indexed:true,name:"batchId",type:"uint256"},{indexed:true,name:"recipient",type:"address"},{indexed:false,name:"amount",type:"uint256"},{indexed:false,name:"reason",type:"string"}] },

  // ── Constructor ───────────────────────────────────────────────────────────
  { type:"constructor", stateMutability:"nonpayable", inputs:[{name:"_council",type:"address[]"},{name:"_threshold",type:"uint256"}] },

  // ── Admin & Setup ─────────────────────────────────────────────────────────
  { type:"function", name:"registerActor",       stateMutability:"nonpayable",
    inputs:[{name:"_wallet",type:"address"},{name:"_role",type:"uint8"},{name:"_name",type:"string"},{name:"_location",type:"string"}],
    outputs:[] },
  { type:"function", name:"registerRetailOutlet", stateMutability:"nonpayable",
    inputs:[{name:"_wallet",type:"address"},{name:"_role",type:"uint8"},{name:"_storeName",type:"string"},{name:"_location",type:"string"},{name:"_outletType",type:"uint8"},{name:"_platformURL",type:"string"}],
    outputs:[] },
  { type:"function", name:"setDepartmentHead",   stateMutability:"nonpayable",
    inputs:[{name:"_dept",type:"uint8"},{name:"_head",type:"address"}],
    outputs:[] },
  { type:"function", name:"deactivateActor",     stateMutability:"nonpayable",
    inputs:[{name:"_wallet",type:"address"}],
    outputs:[] },

  // ── Raw Material Sourcing ─────────────────────────────────────────────────
  { type:"function", name:"sourceMaterial",        stateMutability:"nonpayable",
    inputs:[{name:"_fiberType",type:"uint8"},{name:"_originFarm",type:"string"},{name:"_weightKg",type:"uint256"},{name:"_pricePerKg",type:"uint256"},{name:"_harvestDate",type:"uint256"},{name:"_certifications",type:"string"}],
    outputs:[{name:"materialId",type:"uint256"}] },
  { type:"function", name:"approveMaterialQuality",stateMutability:"nonpayable",
    inputs:[{name:"_materialId",type:"uint256"},{name:"_grade",type:"uint8"}],
    outputs:[] },
  { type:"function", name:"rejectMaterialQuality", stateMutability:"nonpayable",
    inputs:[{name:"_materialId",type:"uint256"},{name:"_reason",type:"string"}],
    outputs:[] },

  // ── Production Batch ──────────────────────────────────────────────────────
  { type:"function", name:"createBatch", stateMutability:"nonpayable",
    inputs:[{ name:"params", type:"tuple",
      components:[{name:"batchCode",type:"string"},{name:"productName",type:"string"},{name:"productDescription",type:"string"},{name:"rawMaterialIds",type:"uint256[]"},{name:"quantityUnits",type:"uint256"},{name:"retailPrice",type:"uint256"}]
    }],
    outputs:[{type:"uint256"}] },
  { type:"function", name:"moveBatchToDepartment",    stateMutability:"nonpayable",
    inputs:[{name:"_batchId",type:"uint256"},{name:"_targetDept",type:"uint8"},{name:"_costToAdd",type:"uint256"},{name:"_notes",type:"string"}],
    outputs:[] },
  { type:"function", name:"approveQC",                stateMutability:"nonpayable",
    inputs:[{name:"_batchId",type:"uint256"},{name:"_notes",type:"string"}],
    outputs:[] },
  { type:"function", name:"rejectQC",                 stateMutability:"nonpayable",
    inputs:[{name:"_batchId",type:"uint256"},{name:"_reason",type:"string"}],
    outputs:[] },
  { type:"function", name:"resubmitAfterQCRejection", stateMutability:"nonpayable",
    inputs:[{name:"_batchId",type:"uint256"},{name:"_remediationNotes",type:"string"}],
    outputs:[] },
  { type:"function", name:"markReadyForDispatch",     stateMutability:"nonpayable",
    inputs:[{name:"_batchId",type:"uint256"},{name:"_finalRetailPrice",type:"uint256"}],
    outputs:[] },
  { type:"function", name:"initiateRecall",            stateMutability:"nonpayable",
    inputs:[{name:"_batchId",type:"uint256"},{name:"_reason",type:"string"}],
    outputs:[] },

  // ── Dispatch & Logistics ──────────────────────────────────────────────────
  { type:"function", name:"createDispatchOrder", stateMutability:"nonpayable",
    inputs:[{ name:"params", type:"tuple",
      components:[{name:"batchId",type:"uint256"},{name:"destinationCustodian",type:"address"},{name:"dispatchType",type:"uint8"},{name:"originLocation",type:"string"},{name:"destinationLocation",type:"string"},{name:"courierName",type:"string"},{name:"estimatedDelivery",type:"uint256"},{name:"shippingCost",type:"uint256"}]
    }],
    outputs:[{type:"uint256"}] },
  { type:"function", name:"confirmDispatch_Origin",    stateMutability:"nonpayable",
    inputs:[{name:"_orderId",type:"uint256"}], outputs:[] },
  { type:"function", name:"confirmDispatch_Logistics", stateMutability:"nonpayable",
    inputs:[{name:"_orderId",type:"uint256"},{name:"_trackingNumber",type:"string"}], outputs:[] },
  { type:"function", name:"confirmDispatch_Finance",   stateMutability:"nonpayable",
    inputs:[{name:"_orderId",type:"uint256"}], outputs:[] },
  { type:"function", name:"addTransitCheckpoint",      stateMutability:"nonpayable",
    inputs:[{name:"_orderId",type:"uint256"},{name:"_location",type:"string"},{name:"_newStatus",type:"uint8"},{name:"_statusNote",type:"string"}], outputs:[] },
  { type:"function", name:"markDispatchFailed",        stateMutability:"nonpayable",
    inputs:[{name:"_orderId",type:"uint256"},{name:"_reason",type:"string"}], outputs:[] },
  { type:"function", name:"confirmReceipt",            stateMutability:"nonpayable",
    inputs:[{name:"_orderId",type:"uint256"},{name:"_deliveryNotes",type:"string"}], outputs:[] },

  // ── Governance ────────────────────────────────────────────────────────────
  { type:"function", name:"proposeGovernanceAction", stateMutability:"nonpayable",
    inputs:[{name:"_proposalHash",type:"bytes32"}], outputs:[{name:"pid",type:"uint256"}] },
  { type:"function", name:"approveProposal",         stateMutability:"nonpayable",
    inputs:[{name:"_pid",type:"uint256"}], outputs:[] },
  { type:"function", name:"isProposalApproved",      stateMutability:"view",
    inputs:[{name:"_pid",type:"uint256"}], outputs:[{type:"bool"}] },

  // ── View / Query ──────────────────────────────────────────────────────────
  { type:"function", name:"getBatchOwnershipHistory", stateMutability:"view",
    inputs:[{name:"_batchId",type:"uint256"}],
    outputs:[{type:"tuple[]", components:[{name:"owner",type:"address"},{name:"ownerName",type:"string"},{name:"transferredAt",type:"uint256"},{name:"transferReason",type:"string"},{name:"statusAtTransfer",type:"uint8"}]}] },
  { type:"function", name:"getBatchDeptLogs", stateMutability:"view",
    inputs:[{name:"_batchId",type:"uint256"}],
    outputs:[{type:"tuple[]", components:[{name:"dept",type:"uint8"},{name:"processedBy",type:"address"},{name:"enteredAt",type:"uint256"},{name:"exitedAt",type:"uint256"},{name:"costAdded",type:"uint256"},{name:"notes",type:"string"},{name:"approved",type:"bool"}]}] },
  { type:"function", name:"getTransitCheckpoints", stateMutability:"view",
    inputs:[{name:"_orderId",type:"uint256"}],
    outputs:[{type:"tuple[]", components:[{name:"orderId",type:"uint256"},{name:"location",type:"string"},{name:"timestamp",type:"uint256"},{name:"statusNote",type:"string"},{name:"updatedBy",type:"address"}]}] },
  { type:"function", name:"getBatchMaterials", stateMutability:"view",
    inputs:[{name:"_batchId",type:"uint256"}], outputs:[{type:"uint256[]"}] },
  { type:"function", name:"getDispatchConsensus", stateMutability:"view",
    inputs:[{name:"_orderId",type:"uint256"}],
    outputs:[{name:"origin",type:"bool"},{name:"logistics",type:"bool"},{name:"finance",type:"bool"},{name:"destination",type:"bool"},{name:"fullyConfirmed",type:"bool"}] },
  { type:"function", name:"getDispatchSigners", stateMutability:"view",
    inputs:[{name:"_orderId",type:"uint256"}],
    outputs:[{name:"originSigner",type:"address"},{name:"logisticsSigner",type:"address"},{name:"financeSigner",type:"address"},{name:"destinationSigner",type:"address"}] },
  { type:"function", name:"getBatchCostBreakdown", stateMutability:"view",
    inputs:[{name:"_batchId",type:"uint256"}],
    outputs:[{name:"rawMaterialCost",type:"uint256"},{name:"productionCost",type:"uint256"},{name:"finalCost",type:"uint256"},{name:"retailPrice",type:"uint256"},{name:"margin",type:"uint256"}] },
  { type:"function", name:"getActorCount",   stateMutability:"view", inputs:[], outputs:[{type:"uint256"}] },
  { type:"function", name:"getCouncilSize",  stateMutability:"view", inputs:[], outputs:[{type:"uint256"}] },
  { type:"function", name:"hasRole",         stateMutability:"view",
    inputs:[{name:"_wallet",type:"address"},{name:"_role",type:"uint8"}], outputs:[{type:"bool"}] },
  { type:"function", name:"getOutletInventory", stateMutability:"view",
    inputs:[{name:"_outlet",type:"address"},{name:"_batchId",type:"uint256"}], outputs:[{type:"uint256"}] },

  // ── Public State Getters ──────────────────────────────────────────────────
  { type:"function", name:"admin",                  stateMutability:"view", inputs:[], outputs:[{type:"address"}] },
  { type:"function", name:"proposalCount",          stateMutability:"view", inputs:[], outputs:[{type:"uint256"}] },
  { type:"function", name:"governanceThreshold",    stateMutability:"view", inputs:[], outputs:[{type:"uint256"}] },
  { type:"function", name:"materialCount",          stateMutability:"view", inputs:[], outputs:[{type:"uint256"}] },
  { type:"function", name:"batchCount",             stateMutability:"view", inputs:[], outputs:[{type:"uint256"}] },
  { type:"function", name:"dispatchCount",          stateMutability:"view", inputs:[], outputs:[{type:"uint256"}] },
  { type:"function", name:"departmentsInitialized", stateMutability:"view", inputs:[], outputs:[{type:"bool"}] },
  { type:"function", name:"isCouncilMember",        stateMutability:"view", inputs:[{name:"",type:"address"}], outputs:[{type:"bool"}] },
  { type:"function", name:"actors",                 stateMutability:"view",
    inputs:[{name:"",type:"address"}],
    outputs:[{name:"wallet",type:"address"},{name:"role",type:"uint8"},{name:"name",type:"string"},{name:"location",type:"string"},{name:"isActive",type:"bool"},{name:"registeredAt",type:"uint256"},{name:"totalTransactions",type:"uint256"},{name:"reputationScore",type:"uint256"}] },
  { type:"function", name:"rawMaterials", stateMutability:"view",
    inputs:[{name:"",type:"uint256"}],
    outputs:[{name:"materialId",type:"uint256"},{name:"fiberType",type:"uint8"},{name:"originFarm",type:"string"},{name:"suppliedBy",type:"address"},{name:"weightKg",type:"uint256"},{name:"pricePerKg",type:"uint256"},{name:"totalCost",type:"uint256"},{name:"grade",type:"uint8"},{name:"qualityApproved",type:"bool"},{name:"approvedBy",type:"address"},{name:"harvestDate",type:"uint256"},{name:"receivedAt",type:"uint256"},{name:"certifications",type:"string"},{name:"isConsumed",type:"bool"}] },
  { type:"function", name:"batches", stateMutability:"view",
    inputs:[{name:"",type:"uint256"}],
    outputs:[{name:"batchId",type:"uint256"},{name:"batchCode",type:"string"},{name:"productName",type:"string"},{name:"productDescription",type:"string"},{name:"primaryFiber",type:"uint8"},{name:"quantityUnits",type:"uint256"},{name:"totalWeightKg",type:"uint256"},{name:"rawMaterialCost",type:"uint256"},{name:"productionCost",type:"uint256"},{name:"finalCost",type:"uint256"},{name:"retailPrice",type:"uint256"},{name:"status",type:"uint8"},{name:"currentDept",type:"uint8"},{name:"currentCustodian",type:"address"},{name:"isFinished",type:"bool"},{name:"isRecalled",type:"bool"},{name:"createdAt",type:"uint256"},{name:"lastUpdatedAt",type:"uint256"},{name:"qcNotes",type:"string"},{name:"qcInspector",type:"address"}] },
  { type:"function", name:"dispatchOrders", stateMutability:"view",
    inputs:[{name:"",type:"uint256"}],
    outputs:[{name:"orderId",type:"uint256"},{name:"batchId",type:"uint256"},{name:"dispatchType",type:"uint8"},{name:"originCustodian",type:"address"},{name:"destinationCustodian",type:"address"},{name:"originLocation",type:"string"},{name:"destinationLocation",type:"string"},{name:"courierName",type:"string"},{name:"trackingNumber",type:"string"},{name:"estimatedDelivery",type:"uint256"},{name:"actualDelivery",type:"uint256"},{name:"transitStatus",type:"uint8"},{name:"shippingCost",type:"uint256"},{name:"createdAt",type:"uint256"},{name:"dispatchedAt",type:"uint256"},{name:"originConfirmed",type:"bool"},{name:"logisticsConfirmed",type:"bool"},{name:"financeConfirmed",type:"bool"},{name:"destinationConfirmed",type:"bool"},{name:"originSigner",type:"address"},{name:"logisticsSigner",type:"address"},{name:"financeSigner",type:"address"},{name:"destinationSigner",type:"address"},{name:"deliveryNotes",type:"string"}] },
  { type:"function", name:"departments", stateMutability:"view",
    inputs:[{name:"",type:"uint8"}],
    outputs:[{name:"dept",type:"uint8"},{name:"deptName",type:"string"},{name:"deptHead",type:"address"},{name:"isOperational",type:"bool"},{name:"batchesProcessed",type:"uint256"}] },
] as const;
